//>>built
define("esri/layers/ArcGISImageServiceVectorLayer","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/_base/json dojo/sniff ../kernel ../lang ./GraphicsLayer ./ImageServiceLayerMixin ./pixelFilters/VectorFieldPixelFilter ../renderers/VectorFieldRenderer ../geometry/Point ../geometry/Extent ../graphic dojox/gfx".split(" "),function(l,m,C,r,t,u,k,v,w,x,p,y,z,A,n){l=l([v,w],{declaredClass:"esri.layers.ArcGISImageServiceVectorLayer",constructor:function(a,c){this.symbolTileSize=c&&c.symbolTileSize?
c.symbolTileSize:50;this._maxMag=this._minMag=null;var b=m.clone(this._params);delete b.imageServiceParameters;delete b.pixelFilter;delete b.rendererStyle;delete b.symbolTileSize;this._initialize(a,c);this.renderer||this.setVectorRendererStyle(c&&c.rendererStyle?c.rendererStyle:p.STYLE_SINGLE_ARROW);this.geometryType="esriGeometryPoint";this.symbolTileSizeUnits="Pixels";m.mixin(this._params,b)},getField:function(a){return this._getField(a,!0)},setVectorRendererStyle:function(a){this.rendererStyle=
a;this._updateVectorFieldRenderer();this.useDefaultRenderer=!0},setRenderer:function(a){a&&(this.vectorFieldPixelFilter=this.vectorFieldPixelFilter||new x,this.vectorFieldPixelFilter.setUnits(a.inputUnit,a.outputUnit));this.useDefaultRenderer=!1;this.inherited(arguments)},getFlowRepresentation:function(){return this.renderer&&this.renderer.flowRepresentation||this._vectorFlowRepresentation},onResume:function(){this.inherited(arguments);this._toggleTime()},onSuspend:function(){this.inherited(arguments);
this._toggleTime()},_fixSymbolTileSize:function(){this.renderer&&(this.renderer.symbolTileSize?this.symbolTileSize=this.renderer.symbolTileSize:this.renderer.symbolTileSize=this.symbolTileSize)},_refresh:function(a){if(10>t("ie"))this.onError(Error("Unable to refresh. This layer is not supported in the current browser."));else if(this._map){this._fixSymbolTileSize();this.setImageFormat("LERC",!0);a=this.fullExtent&&this.fullExtent.xmin;var c=this.fullExtent&&this.fullExtent.ymax,b=m.clone(this._map.extent),
f=1/this.symbolTileSize*this._map.width;f=f?Math.ceil(f):50;var d=1/this.symbolTileSize*this._map.height;d=d?Math.ceil(d):Math.ceil((b.ymax-b.ymin)/(b.xmax-b.xmin)*f);var e=(b.xmax-b.xmin)/f,h=(b.ymax-b.ymin)/d;b.xmin=a+Math.floor((b.xmin-a)/e)*e;b.xmax=a+Math.ceil((b.xmax-a)/e)*e;b.ymin=c+Math.floor((b.ymin-c)/h)*h;b.ymax=c+Math.ceil((b.ymax-c)/h)*h;this._requestData(b,f,d)}},_drawPixelData:function(){this.clear();if(this.pixelData){var a=this.pixelData.pixelBlock,c=this.pixelData.extent,b=this.pixelData.locations,
f=k.isDefined(a.mask)&&0<a.mask.length;if(a&&c&&b){if(this.useDefaultRenderer&&this.renderer&&(!k.isDefined(this._minMag)||!k.isDefined(this._maxMag))){var d=this._getServiceMinMaxStats();d?(this._minMag=d.min,this._maxMag=d.max):(this._minMag=a.statistics[0].minValue,this._maxMag=a.statistics[0].maxValue);d={type:"sizeInfo",minSize:n.px2pt(.2*this.symbolTileSize),maxSize:n.px2pt(.8*this.symbolTileSize),minDataValue:this._minMag,maxDataValue:this._maxMag};var e=[];e.push(d);e.push({type:"colorInfo"});
this.renderer.setVisualVariables(e)}var h=e=d=0,q=c.spatialReference?c.spatialReference._getInfo():null;for(d=0;d<a.height;d++)for(e=0;e<a.width;e++,h++){var g=b[h];if((!f||a.mask[h])&&g&&2===g.length){g=new y(g[0],g[1],c.spatialReference);q&&(g.x=z.prototype._normalizeX(g.x,q).x);var B={Magnitude:a.pixels[0][h],Direction:a.pixels[1][h],Location:r.toJson(g.toJson())};g=new A(g,null,B);this.add(g)}}}}},_getServiceMinMaxStats:function(){if(!k.isDefined(this.minValues)||!k.isDefined(this.maxValues)||
2>this.minValues.length||2>this.maxValues.length)return null;var a=this.minValues[0],c=this.maxValues[0],b=this.minValues[1],f=this.maxValues[1];if(this.pixelFilter&&a&&c&&b&&f){var d=[];d.push([a,c]);d.push([b,f]);b=this._createPixelData(d);this.pixelFilter(b);b&&b.pixelBlock&&b.pixelBlock.pixels&&0<b.pixelBlock.pixels.length&&(a=b.pixelBlock.pixels[0][0],c=b.pixelBlock.pixels[0][1])}return a&&c?{min:a,max:c}:null},_updateVectorFieldRenderer:function(){var a={type:"sizeInfo",minSize:n.px2pt(.2*this.symbolTileSize),
maxSize:n.px2pt(.8*this.symbolTileSize),minDataValue:this._minMag,maxDataValue:this._maxMag},c=[];c.push(a);a=new p({style:this.rendererStyle,visualVariables:c,flowRepresentation:this._vectorFlowRepresentation});this.setRenderer(a)},_getField:function(a,c){if(k.isDefined(a))return c&&(a=a.toLowerCase()),"magnitude"!==a&&"direction"!==a?null:{name:a,alias:a,domain:null,editable:!1,length:50,type:"esriFieldTypeDouble"}},_requestDataErrorHandler:function(a){"CancelError"!==a.name&&(this.clear(),this.onError(a))},
_setFlowRepresentation:function(a){this.renderer&&this.renderer.flowRepresentation?this._vectorFlowRepresentation=this.renderer.flowRepresentation:a&&this.renderer&&k.isDefined(a.FlowDirection)&&a.FlowDirection&&(this._vectorFlowRepresentation="oceanographic"===a.FlowDirection.toLowerCase()?this.renderer.FLOW_TO:this.renderer.FLOW_FROM);this.renderer&&(this.renderer.flowRepresentation=this._vectorFlowRepresentation)}});m.setObject("layers.ArcGISImageServiceVectorLayer",l,u);return l});