//>>built
define("dgrid/extensions/ColumnResizer","dojo/_base/declare dojo/on dojo/query dojo/_base/lang dojo/dom dojo/dom-geometry dojo/has ../util/misc put-selector/put dojo/_base/html xstyle/css!../css/extensions/ColumnResizer.css".split(" "),function(I,w,r,E,F,J,y,m,p){function G(a){for(var b=a.length,c=b,d=a[0].length,k=Array(b);b--;)k[b]=Array(d);var h={};for(b=0;b<c;b++)for(var f=k[b],l=a[b],g=0,x=0;g<d;g++){var e=l[x];if("undefined"==typeof f[g]){f[g]=e.id;if(e.rowSpan&&1<e.rowSpan){var q=k;for(var z=
e.rowSpan,A=b,B=g,C=e.id,t=1;t<z;t++)q[A+t][B]=C}if(0<b&&e.colSpan&&1<e.colSpan)for(q=1;q<e.colSpan;q++)if(f[++g]=e.id,e.rowSpan&&1<e.rowSpan){z=k;A=e.rowSpan;B=b;C=g;t=e.id;for(var D=1;D<A;D++)z[B+D][C]=t}h[e.id]=a[0][g].id;x++}}return h}function u(a,b,c,d,k){if(!(0>=c)){var h=a.columns[b];if(h){var f={grid:a,columnId:b,width:c,bubbles:!0,cancelable:!0};d&&(f.parentType=d);if(!a._resizedColumns||w.emit(a.headerNode,"dgrid-columnresize",f))return"auto"===c?delete h.width:(h.width=c,c+="px"),(d=a._columnSizes[b])?
d.set("width",c):d=m.addCssRule("#"+m.escapeCssIdentifier(a.domNode.id)+" .dgrid-column-"+m.escapeCssIdentifier(b,"-"),"width: "+c+";"),a._columnSizes[b]=d,!1!==k&&a.resize(),!0}}}var n,H=0,v={create:function(){n=p("div.dgrid-column-resizer")},destroy:function(){p(n,"!");n=null},show:function(a){a=J.position(a.domNode,!0);n.style.top=a.y+"px";n.style.height=a.h+"px";p(document.body,n)},move:function(a){n.style.left=a+"px"},hide:function(){n.parentNode.removeChild(n)}};return I("dgrid.extensions.ColumnResizer",
null,{resizeNode:null,minWidth:40,adjustLastColumn:!0,_resizedColumns:!1,buildRendering:function(){this.inherited(arguments);H++||v.create()},destroy:function(){this.inherited(arguments);for(var a in this._columnSizes)this._columnSizes[a].remove();--H||v.destroy()},resizeColumnWidth:function(a,b){return u(this,a,b)},configStructure:function(){var a=this._oldColumnSizes=E.mixin({},this._columnSizes),b;this._resizedColumns=!1;this._columnSizes={};this.inherited(arguments);for(b in a)b in this._columnSizes||
a[b].remove();delete this._oldColumnSizes},_configColumn:function(a){this.inherited(arguments);var b=a.id,c;"width"in a&&((c=this._oldColumnSizes[b])?c.set("width",a.width+"px"):c=m.addCssRule("#"+m.escapeCssIdentifier(this.domNode.id)+" .dgrid-column-"+m.escapeCssIdentifier(b,"-"),"width: "+a.width+"px;"),this._columnSizes[b]=c)},renderHeader:function(){this.inherited(arguments);var a=this;if(this.columnSets&&this.columnSets.length)for(var b=this.columnSets.length;b--;)var c=E.mixin(c||{},G(this.columnSets[b]));
else this.subRows&&1<this.subRows.length&&(c=G(this.subRows));b=r(".dgrid-cell",a.headerNode);for(var d=b.length;d--;){var k=b[d],h=k.columnId,f=a.columns[h],l=k.childNodes;if(f&&!1!==f.resizable){f=p("div.dgrid-resize-header-container");for(k.contents=f;0<l.length;)p(f,l[0]);p(k,f,"div.dgrid-resize-handle.resizeNode-"+m.escapeCssIdentifier(h,"-")).columnId=c&&c[h]||h}}a.mouseMoveListen||(w(a.headerNode,".dgrid-resize-handle:mousedown"+(y("touch")?",.dgrid-resize-handle:touchstart":""),function(g){a._resizeMouseDown(g,
this);a.mouseMoveListen.resume();a.mouseUpListen.resume()}),a._listeners.push(a.mouseMoveListen=w.pausable(document,"mousemove"+(y("touch")?",touchmove":""),m.throttleDelayed(function(g){a._updateResizerPosition(g)}))),a._listeners.push(a.mouseUpListen=w.pausable(document,"mouseup"+(y("touch")?",touchend":""),function(g){a._resizeMouseUp(g);a.mouseMoveListen.pause();a.mouseUpListen.pause()})),a.mouseMoveListen.pause(),a.mouseUpListen.pause())},_resizeMouseDown:function(a,b){a.preventDefault();F.setSelectable(this.domNode,
!1);this._startX=this._getResizeMouseLocation(a);this._targetCell=r(".dgrid-column-"+m.escapeCssIdentifier(b.columnId,"-"),this.headerNode)[0];this._updateResizerPosition(a);v.show(this)},_resizeMouseUp:function(a){var b=this._columnSizes,c;this.adjustLastColumn&&(c=this.headerNode.clientWidth-1);if(!this._resizedColumns){var d=r(".dgrid-cell",this.headerNode);this.columnSets&&this.columnSets.length?d=d.filter(function(e){return"0"==e.columnId.split("-")[0]&&!(e.columnId in b)}):this.subRows&&1<this.subRows.length&&
(d=d.filter(function(e){return"0"==e.columnId.charAt(0)&&!(e.columnId in b)}));var k=d.map(function(e){return e.offsetWidth});d.forEach(function(e,q){u(this,e.columnId,k[q],null,!1)},this);this._resizedColumns=!0}F.setSelectable(this.domNode,!0);d=this._targetCell;var h=this._getResizeMouseLocation(a)-this._startX,f=d.offsetWidth+h,l=this._getResizedColumnWidths(),g=l.totalWidth;l=l.lastColId;var x=r(".dgrid-column-"+m.escapeCssIdentifier(l,"-"),this.headerNode)[0].offsetWidth;f<this.minWidth&&(f=
this.minWidth);u(this,d.columnId,f,a.type)&&d.columnId!=l&&this.adjustLastColumn&&(g+h<c?u(this,l,"auto",a.type):x-h<=this.minWidth&&u(this,l,this.minWidth,a.type));v.hide();delete this._startX;delete this._targetCell},_updateResizerPosition:function(a){if(this._targetCell){a=this._getResizeMouseLocation(a);var b=this._targetCell.offsetWidth,c=a;b+(a-this._startX)<this.minWidth&&(c=this._startX-(b-this.minWidth));v.move(c)}},_getResizeMouseLocation:function(a){var b=0;a.pageX?b=a.pageX:a.clientX&&
(b=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft);return b},_getResizedColumnWidths:function(){var a=0,b=r((this.columnSets?".dgrid-column-set-cell ":"")+"tr:first-child .dgrid-cell",this.headerNode),c=b.length;if(!c)return{};for(var d=b[c-1].columnId;c--;)a+=b[c].offsetWidth;return{totalWidth:a,lastColId:d}}})});