//>>built
define("esri/dijit/analysis/HelpWindow","require dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/_base/event dojo/_base/kernel dojo/aspect dojo/has dojo/dom-construct dojo/dom-class dojo/dom-attr dojo/dom-style dojo/query dojo/window dojo/dom-geometry dijit/_Widget dijit/TooltipDialog dijit/popup ../../kernel ../../lang ../../urlUtils ../../request ../_EventedWidget dojo/i18n!../../nls/jsapi".split(" "),function(q,r,m,f,G,H,k,v,w,I,J,K,x,y,z,A,B,C,n,D,t,E,F,L,u){m=m([B],
{declaredClass:"esri.dijit.analysis.HelpWindow",i18n:null,onlineHelpMap:null,showLearnMore:!1,"class":"esriAnalyisHelpWindow",constructor:function(b){this.isPortal=b&&b.isPortal},postMixInProperties:function(){this.inherited(arguments);this.i18n={};f.mixin(this.i18n,u.common);f.mixin(this.i18n,u.analysisHelp)},postCreate:function(){this.inherited(arguments);var b=["ar","he"],a;for(a=0;a<b.length;a+=1){var d=b[a];k.locale&&-1!==k.locale.indexOf(d)&&(-1!==k.locale.indexOf("-")?-1!==k.locale.indexOf(d+
"-")&&(this._isRightToLeft=!0):this._isRightToLeft=!0)}b=q.toUrl(this.isPortal?"./help/helpmap_enterprise.json":"./help/helpmap.json");F({url:b}).then(f.hitch(this,function(c){this.onlineHelpMap=c.map}),function(c){});this._initSelfHelpMap()},_getAbsoluteUrl:function(b){var a=E.getProtocolForWebResource();if(/^https?:/i.test(b))return b;if(/^\/\//i.test(b))return a+b;if(/^\//i.test(b))return a+"//"+window.location.host+b},_computeSize:function(b){var a={w:400,h:200};w("esri-mobile")?a={w:"50%",h:"90%"}:
-1!==b.indexOf("Category")?(a.w=400,a.h=320):-1!==b.indexOf("Tool")?(a.w=400,a.h=320):-1!==b.indexOf("toolDescription")&&(a.w=400,a.h=520);return a},_initSelfHelpMap:function(){this.isPortal&&this.portalSelf&&this.portalSelf.helpMap&&(this.selfHelpMap=this.portalSelf.helpMap.m)},_setHelpTopicAttr:function(b){this.tooltipHelpDlg&&(n.close(this.tooltipHelpDlg),this.tooltipHelpDlg.destroy(),this.tooltipHelpDlg=null);var a="";this.showLearnMore=!1;var d=this._analysisGpServer&&-1!==this._analysisGpServer.indexOf("dev")?
"dev":this._analysisGpServer&&-1!==this._analysisGpServer.indexOf("qa")?"uat":"";a=this.isPortal?"-PortalOnly":"-OnlineOnly";var c=f.clone(k.locale);var g="es-es es-mx fr-fr fr-ch it-ch it-it de-de de-ch".split(" ");"nb"===c?c="no":-1!==r.indexOf(g,c)&&(c=c.split("-")[0]);var h="ar bg bs ca cs da de es el et fi fr he hr hu id it ja ko lt lv ru nl no pl pt-br pt-pt ro sl sk sv sr th tr uk vi zh-cn zh-hk zh-tw".split(" ");var p="ar de es fr it ja ko ru pl pt-br zh-cn".split(" ");if("SHOWHELPURL"===
b)g=this.helpIdUrl,this.showLearnMore=!1;else{g=q.toUrl("esri/dijit/analysis/help/"+this.helpFileName+".html");var e=this.helpFileName;if(t.isDefined(this.onlineHelpMap)&&t.isDefined(this.onlineHelpMap[e])&&t.isDefined(this.onlineHelpMap[e][b])){this.showLearnMore=!0;var l="https://doc"+d+".arcgis.com/en/arcgis-online/analyze/"+this.onlineHelpMap[e][b];this.isPortal&&this.helpBase&&this.selfHelpMap&&(l=this.helpBase+this.selfHelpMap[this.onlineHelpMap[e][b]])}-1!==r.indexOf(h,c)&&(-1!==c.indexOf("-")&&
(c=c.split("-"),c=c[0]+"-"+c[1].toUpperCase()),g=q.toUrl("esri/dijit/analysis/help/"+c+"/"+this.helpFileName+".html"));-1!==r.indexOf(p,c)&&this.showLearnMore&&(l="https://doc"+d+".arcgis.com/"+c+"/arcgis-online/analyze/"+this.onlineHelpMap[e][b],this.isPortal&&this.helpBase&&this.selfHelpMap?l=this.helpBase+this.selfHelpMap[this.onlineHelpMap[e][b]]:this.isPortal&&!this.helpBase&&(l="https://server"+d+".arcgis.com/"+c+"/portal/latest/use/"+this.onlineHelpMap[e][b]))}this._size=d=this._computeSize(b);
this.tooltipHelpDlg=new C({preload:!0,content:"\x3cdiv class\x3d'' style\x3d'position:relative'\x3cdiv class\x3d'sizer content'\x3e\x3cdiv class\x3d'contentPane'\x3e\x3cdiv class\x3d'esriFloatTrailing' style\x3d'padding:0;'\x3e\x3ca href\x3d'#' class\x3d'esriAnalysisCloseIcon' title\x3d'"+this.i18n.close+"'\x3e\x3c/a\x3e\x3c/div\x3e\x3ciframe frameborder\x3d'0'  id\x3d'"+b+"' src\x3d'"+g+"#"+b+a+"' width\x3d'"+d.w+"' height\x3d'"+d.h+"' marginheight\x3d'0' marginwidth\x3d'0'\x3e\x3c/iframe\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d'sizer'\x3e\x3cdiv class\x3d'actionsPane'\x3e\x3cdiv class\x3d'actionList"+
(this.showLearnMore?"'\x3e":" hidden'\x3e")+"\x3ca class\x3d'action zoomTo' href\x3d'"+(this.showLearnMore?l:"#")+"' target\x3d'_help'\x3e"+this.i18n.learnMore+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e","class":"esriHelpPopup esriHelpPopupWrapper esriAnalyisHelpWindow"});this.tooltipHelpDlg.startup()},show:function(b,a){this.helpFileName=a.helpFileName;this._analysisGpServer=a.analysisGpServer;this.isPortal=a.isPortal;this.helpBase=a.helpBase;a.portalSelf&&(this.portalSelf=
a.portalSelf);this.selfHelpMap||this._initSelfHelpMap();a.analysisMode&&(this.analysisMode=a.analysisMode);a.showHelpFromUrl&&a.helpUrl&&(this.showHelpFromUrl=a.showHelpFromUrl,this.helpIdUrl=a.helpUrl,a.helpId="SHOWHELPURL");this.set("helpTopic",a.helpId);var d=v.after(n,"open",f.hitch(this,function(){y(".esriAnalysisCloseIcon",this.tooltipHelpDlg.domNode).on("click",f.hitch(this,this.close));d.remove()})),c=b.pageX,g=z.getBox(),h;var p=!1;if(a.helpParentNode)var e=a.helpParentNode;e&&(h=A.position(e));
h&&g.w-b.pageX<h.w?(p=!0,c=h.x-this._size.w-10,this._isRightToLeft&&(c-=10)):this._isRightToLeft&&c-40<this._size.w&&(c=h.w+this._size.w+80);n.open({popup:this.tooltipHelpDlg,x:!0===this._isRightToLeft||p?c-40:c+40,y:b.screenY-b.pageY+10,onCancel:f.hitch(this,function(){this.close()}),onExecute:function(){this.close()}});this.tooltipHelpDlg.domNode.parentNode&&x.set(this.tooltipHelpDlg.domNode.parentNode,"overflowY","hidden")},close:function(b,a){n.close(this.tooltipHelpDlg)}});f.setObject("dijit.analysis.HelpWindow",
m,D);return m});