//>>built
define("dgrid/List","dojo/_base/kernel dojo/_base/declare dojo/dom dojo/on dojo/query dojo/has ./util/misc dojo/has!touch?./TouchScroll xstyle/has-class put-selector/put dojo/_base/sniff xstyle/css!./css/dgrid.css".split(" "),function(H,I,Q,B,R,h,v,S,T,k){function x(a,b){return R("#"+v.escapeCssIdentifier(a),b)[0]}function J(a,b){k(document.body,a,".dgrid-scrollbar-measure");b=a["offset"+b]-a["client"+b];a.className="";a.parentNode&&document.body.removeChild(a);return b}function D(a){var b=a?"."+
a.replace(K,"."):"";this._class&&(b="!"+this._class.replace(K,"!")+b);k(this.domNode,b);this._class=a}function L(){return this._class}function M(){return{x:this.bodyNode.scrollLeft,y:this.bodyNode.scrollTop}}function N(a){"undefined"!==typeof a.x&&(this.bodyNode.scrollLeft=a.x);"undefined"!==typeof a.y&&(this.bodyNode.scrollTop=a.y)}T("mozilla","opera","webkit","ie","ie-6","ie-6-7","quirks","no-quirks","touch");var w,E;h.add("dom-scrollbar-width",function(a,b,c){return J(c,"Width")});h.add("dom-scrollbar-height",
function(a,b,c){return J(c,"Height")});h.add("dom-rtl-scrollbar-left",function(a,b,c){a=k("div");k(document.body,c,".dgrid-scrollbar-measure[dir\x3drtl]");k(c,a);b=!!h("ie")||!!h("trident")||a.offsetLeft>=h("dom-scrollbar-width");c.className="";c.parentNode&&document.body.removeChild(c);k(a,"!");c.removeAttribute("dir");return b});var U=0,K=/ +/g,V=7>h("ie")&&!h("quirks")?function(){if(this._started){var a=document.documentElement;var b=a.clientWidth;a=a.clientHeight;var c=this._prevWinDims||[];if(c[0]!==
b||c[1]!==a)this.resize(),this._prevWinDims=[b,a]}}:function(){this._started&&this.resize()};return I("dgrid.List",h("touch")?S:null,{tabableHeader:!1,showHeader:!1,showFooter:!1,maintainOddEven:!0,cleanAddedRules:!0,useTouchScroll:null,addUiClasses:!0,shouldObserveStore:!0,cleanEmptyObservers:!0,highlightDuration:250,postscript:function(a,b){var c=this;(this._Row=function(e,d,f){this.id=e;this.data=d;this.element=f}).prototype.remove=function(){c.removeRow(this.element)};b&&(this.srcNodeRef=b=b.nodeType?
b:x(b));this.create(a,b)},listType:"list",create:function(a,b){b=this.domNode=b||k("div");if(a){this.params=a;I.safeMixin(this,a);var c=a["class"]||a.className||b.className;this._sort=a.sort||[];delete this.sort}else this._sort=[];this.observers=[];this._numObservers=0;this._listeners=[];this._rowIdToObject={};this.postMixInProperties&&this.postMixInProperties();this.id=b.id=b.id||this.id||"dgrid_"+U++;null===this.useTouchScroll&&(this.useTouchScroll=!h("dom-scrollbar-width"));this.buildRendering();
c&&D.call(this,c);this.postCreate();delete this.srcNodeRef;this.domNode.offsetHeight&&this.startup()},buildRendering:function(){var a=this.domNode,b=this.addUiClasses,c=this;var e=this.isRTL="rtl"==(document.body.dir||document.documentElement.dir||document.body.style.direction).toLowerCase();a.className="";k(a,"[role\x3dgrid].dgrid.dgrid-"+this.listType+(b?".ui-widget":""));var d=this.headerNode=k(a,"div.dgrid-header.dgrid-header-row"+(b?".ui-widget-header":"")+(this.showHeader?"":".dgrid-header-hidden"));
(h("quirks")||8>h("ie"))&&k(a,"div.dgrid-spacer");var f=this.bodyNode=k(a,"div.dgrid-scroller");h("ff")&&(f.tabIndex=-1);this.headerScrollNode=k(a,"div.dgrid-header.dgrid-header-scroll.dgrid-scrollbar-width"+(b?".ui-widget-header":""));var q=this.footerNode=k("div.dgrid-footer"+(this.showFooter?"":".dgrid-footer-hidden"));k(a,q);e&&(a.className+=" dgrid-rtl"+(h("dom-rtl-scrollbar-left")?" dgrid-rtl-swap":""));B(f,"scroll",function(g){c.showHeader&&(d.scrollLeft=g.scrollLeft||f.scrollLeft);g.stopPropagation();
B.emit(a,"scroll",{scrollTarget:f})});this.configStructure();this.renderHeader();this.contentNode=this.touchNode=k(this.bodyNode,"div.dgrid-content"+(b?".ui-widget-content":""));this._listeners.push(this._resizeHandle=B(window,"resize",v.throttleDelayed(V,this)))},postCreate:h("touch")?function(){this.useTouchScroll&&this.inherited(arguments)}:function(){},startup:function(){this._started||(this.inherited(arguments),this._started=!0,this.resize(),this.set("sort",this._sort))},configStructure:function(){},
resize:function(){var a=this.bodyNode,b=this.headerNode,c=this.footerNode,e=b.offsetHeight,d=this.showFooter?c.offsetHeight:0,f=h("quirks")||7>h("ie");this.headerScrollNode.style.height=a.style.marginTop=e+"px";a.style.marginBottom=d+"px";f&&(a.style.height="",a.style.height=Math.max(this.domNode.offsetHeight-e-d,0)+"px",d&&(c.style.bottom="1px",setTimeout(function(){c.style.bottom=""},0)));w||(w=h("dom-scrollbar-width"),E=h("dom-scrollbar-height"),h("ie")&&(w++,E++),v.addCssRule(".dgrid-scrollbar-width",
"width: "+w+"px"),v.addCssRule(".dgrid-scrollbar-height","height: "+E+"px"),17==w||f||(v.addCssRule(".dgrid-header-row","right: "+w+"px"),v.addCssRule(".dgrid-rtl-swap .dgrid-header-row","left: "+w+"px")));f&&(b.style.width=a.clientWidth+"px",setTimeout(function(){b.scrollLeft=a.scrollLeft},0))},addCssRule:function(a,b){a=v.addCssRule(a,b);this.cleanAddedRules&&this._listeners.push(a);return a},on:function(a,b){a=B(this.domNode,a,b);h("dom-addeventlistener")||this._listeners.push(a);return a},cleanup:function(){var a=
this.observers,b;for(b in this._rowIdToObject)if(this._rowIdToObject[b]!=this.columns){var c=x(b,this.domNode);c&&this.removeRow(c,!0)}for(b=0;b<a.length;b++)(c=a[b])&&c.cancel();this.observers=[];this._numObservers=0;this.preload=null},destroy:function(){if(this._listeners){for(var a=this._listeners.length;a--;)this._listeners[a].remove();delete this._listeners}this._started=!1;this.cleanup();k(this.domNode,"!");this.useTouchScroll&&this.inherited(arguments)},refresh:function(){this.cleanup();this._rowIdToObject=
{};this._autoId=0;this.contentNode.innerHTML="";this.scrollTo({x:0,y:0})},newRow:function(a,b,c,e,d){if(b){var f=this.insertRow(a,b,c,e,d);k(f,".dgrid-highlight"+(this.addUiClasses?".ui-state-highlight":""));setTimeout(function(){k(f,"!dgrid-highlight!ui-state-highlight")},this.highlightDuration);return f}},adjustRowIndices:function(a){var b=a.rowIndex;if(-1<b){do-1<a.rowIndex&&(this.maintainOddEven&&-1<(a.className+" ").indexOf("dgrid-row ")&&k(a,"."+(1==b%2?"dgrid-row-odd":"dgrid-row-even")+"!"+
(0==b%2?"dgrid-row-odd":"dgrid-row-even")),a.rowIndex=b++);while((a=a.nextSibling)&&a.rowIndex!=b)}},renderArray:function(a,b,c){function e(){var n=arguments;if(-1<z)for(var t=0;t<n.length;t++){var p=n[t],u=r[p?0:r.length-1];if(u=u&&d(u)){var l=u[p?"previousSibling":"nextSibling"];l&&(l=g.row(l));l&&l.element!=u&&(p=p?"unshift":"push",a[p](l.data),r[p](l.element),c.count++)}}}function d(n){return!Q.isDescendant(n,g.domNode)&&x(n.id)?g.row(n.id.slice(g.id.length+5)).element:n}function f(n){A=g.insertRow(n,
O,null,W++,c);A.observerIndex=z;return A}function q(n){F=n.slice(0);(y=b?b.parentNode:g.contentNode)&&y.parentNode&&(y!==g.contentNode||n.length)?(y.insertBefore(O,b||null),(A=n[n.length-1])&&g.adjustRowIndices(A)):P[z]&&g.cleanEmptyObservers&&g._onEmptyRender(z);r=n;G&&(G.rows=r)}c=c||{};var g=this,W=c.start||0,P=this.observers,y;b||(this._lastCollection=a);if(a.observe&&this.shouldObserveStore){g._numObservers++;var G=a.observe(function(n,t,p){var u;if(-1<t&&r[t]){var l=r.splice(t,1)[0];l.parentNode==
y&&((u=l.nextSibling)&&t!=p&&u.rowIndex--,g.removeRow(l));c.count--;g._processScroll&&g._processScroll()}if(-1<p){if(r.length)if(0===p)var m=(m=r[p])&&d(m);else{if(m=r[p-1])m=d(m),m=(m.connected||m).nextSibling}else m=g._getFirstRowSibling&&g._getFirstRowSibling(y);l&&m&&l.id===m.id&&(m=(m.connected||m).nextSibling);m&&!m.parentNode&&(m=x(m.id));l=b&&b.parentNode||m&&m.parentNode||g.contentNode;if(l=g.newRow(n,l,m,c.start+p,c))if(l.observerIndex=z,r.splice(p,0,l),!u||p<t)u=(u=l.previousSibling)&&
u.rowIndex+1!=l.rowIndex&&0!=l.rowIndex?u:l;c.count++}0===t?e(1,1):t===a.length-(-1===p?0:1)&&e(0,0);t!=p&&u&&g.adjustRowIndices(u);g._onNotification(r,n,t,p)},!0);var z=P.push(G)-1}var O=document.createDocumentFragment(),A,F;if(a.map){var r=a.map(f,console.error);if(r.then)return a.then(function(n){a=n;return r.then(function(t){q(t);e(1,1,0,0);return F})})}else{r=[];for(var C=0,X=a.length;C<X;C++)r[C]=f(a[C])}q(r);e(1,1,0,0);return F},_onEmptyRender:function(a){"undefined"!==typeof a&&(this.observers[a].cancel(),
this.observers[a]=0,this._numObservers--)},_onNotification:function(a,b,c,e){},renderHeader:function(){},_autoId:0,insertRow:function(a,b,c,e,d){var f=d.parentId;f=this.id+"-row-"+(f?f+"-":"")+(this.store&&this.store.getIdentity?this.store.getIdentity(a):this._autoId++);var q=x(f,this.domNode),g=q&&q.previousSibling;q&&(q===c&&(c=(c.connected||c).nextSibling),this.removeRow(q));q=this.renderRow(a,d);q.className=(q.className||"")+" dgrid-row "+(1==e%2?"dgrid-row-odd":"dgrid-row-even")+(this.addUiClasses?
" ui-state-default":"");this._rowIdToObject[q.id=f]=a;b.insertBefore(q,c||null);g&&this.adjustRowIndices(g);q.rowIndex=e;return q},renderRow:function(a,b){return k("div",""+a)},removeRow:function(a,b){a=a.element||a;delete this._rowIdToObject[a.id];b||k(a,"!")},row:function(a){var b;if(a instanceof this._Row)return a;a.target&&a.target.nodeType&&(a=a.target);if(a.nodeType){do{var c=a.id;if(b=this._rowIdToObject[c])return new this._Row(c.substring(this.id.length+5),b,a);a=a.parentNode}while(a&&a!=
this.domNode)}else return"object"==typeof a?b=this.store.getIdentity(a):(b=a,a=this._rowIdToObject[this.id+"-row-"+b]),new this._Row(b,a,x(this.id+"-row-"+b,this.domNode))},cell:function(a){return{row:this.row(a)}},_move:function(a,b,c,e){var d;var f=d=a.element;b=b||1;do if(a=d[0>b?"previousSibling":"nextSibling"]){do if((d=a)&&-1<(d.className+" ").indexOf(c+" ")){f=d;b+=0>b?1:-1;break}while(a=(!e||!d.hidden)&&d[0>b?"lastChild":"firstChild"])}else if(d=d.parentNode,!d||d===this.bodyNode||d===this.headerNode)break;
while(b);return f},up:function(a,b,c){a.element||(a=this.row(a));return this.row(this._move(a,-(b||1),"dgrid-row",c))},down:function(a,b,c){a.element||(a=this.row(a));return this.row(this._move(a,b||1,"dgrid-row",c))},scrollTo:h("touch")?function(a){return this.useTouchScroll?this.inherited(arguments):N.call(this,a)}:N,getScrollPosition:h("touch")?function(){return this.useTouchScroll?this.inherited(arguments):M.call(this)}:M,get:function(a){var b="_get"+a.charAt(0).toUpperCase()+a.slice(1);return"function"===
typeof this[b]?this[b].apply(this,[].slice.call(arguments,1)):this[a]},set:function(a,b){if("object"===typeof a)for(var c in a)this.set(c,a[c]);else c="_set"+a.charAt(0).toUpperCase()+a.slice(1),"function"===typeof this[c]?this[c].apply(this,[].slice.call(arguments,1)):this[a]=b;return this},_getClass:L,_setClass:D,_getClassName:L,_setClassName:D,_setSort:function(a,b){this._sort="string"!=typeof a?a:[{attribute:a,descending:b}];this.refresh();this._lastCollection&&(a.length&&("string"!=typeof a&&
(b=a[0].descending,a=a[0].attribute),this._lastCollection.sort(function(c,e){c=c[a];e=e[a];void 0===c&&(c="");void 0===e&&(e="");return c==e?0:c>e==!b?1:-1})),this.renderArray(this._lastCollection))},sort:function(a,b){H.deprecated("sort(...)",'use set("sort", ...) instead',"dgrid 0.4");this.set("sort",a,b)},_getSort:function(){return this._sort},_setShowHeader:function(a){var b=this.headerNode;this.showHeader=a;k(b,(a?"!":".")+"dgrid-header-hidden");this.renderHeader();this.resize();a&&(b.scrollLeft=
this.getScrollPosition().x)},setShowHeader:function(a){H.deprecated("setShowHeader(...)",'use set("showHeader", ...) instead',"dgrid 0.4");this.set("showHeader",a)},_setShowFooter:function(a){this.showFooter=a;k(this.footerNode,(a?"!":".")+"dgrid-footer-hidden");this.resize()}})});