//>>built
define("dgrid/OnDemandList","./List ./_StoreMixin dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/dom dojo/on ./util/misc put-selector/put".split(" "),function(U,V,W,O,B,X,P,Q,n){return W("dgrid.OnDemandList",[U,V],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,bufferRows:10,farOffRemoval:2E3,queryRowsOverlap:0,pagingMethod:"debounce",pagingDelay:Q.defaultDelay,keepScrollPosition:!1,rowHeight:22,postCreate:function(){this.inherited(arguments);var d=this;P(this.bodyNode,"scroll",
Q[this.pagingMethod](function(e){d._processScroll(e)},null,this.pagingDelay))},destroy:function(){this.inherited(arguments);this._refreshTimeout&&clearTimeout(this._refreshTimeout)},renderQuery:function(d,e){function g(t){n(C,"!");if(t)throw c._refreshDeferred&&(c._refreshDeferred.reject(t),delete c._refreshDeferred),t;}var c=this,a=e&&e.container||this.contentNode,k={query:d,count:0,options:e},b,y=this.preload,q,F={node:n(a,"div.dgrid-preload",{rowIndex:0}),count:0,query:d,next:k,options:e};F.node.style.height=
"0";k.node=b=n(a,"div.dgrid-preload");k.previous=F;b.rowIndex=this.minRowsPerPage;y?((k.next=y.next)&&b.offsetTop>=y.node.offsetTop?k.previous=y:(k.next=y,k.previous=y.previous),k.previous.next=k,k.next.previous=k):this.preload=k;var C=n(b,"-div.dgrid-loading");n(C,"div.dgrid-below").innerHTML=this.loadingMessage;e=O.mixin(this.get("queryOptions"),e,{start:0,count:this.minRowsPerPage},"level"in d?{queryLevel:d.level}:null);this._trackError(function(){return q=d(e)});if("undefined"===typeof q)g();
else return B.when(c.renderArray(q,b,e),function(t){return B.when("undefined"===typeof q.total?q.length:q.total,function(u){var w=t.length,A=b.parentNode,f=c.noDataNode;n(C,"!");"queryLevel"in e||(c._total=u);0===u&&A&&(f&&(n(f,"!"),delete c.noDataNode),c.noDataNode=f=n("div.dgrid-no-data"),A.insertBefore(f,c._getFirstRowSibling(A)),f.innerHTML=c.noDataMessage);for(var h=f=0;h<w;h++)f+=c._calcRowHeight(t[h]);w&&f&&(c.rowHeight=f/w);f=c.rowHeight*c.bufferRows;f>c.farOffRemoval&&(c.farOffRemoval=f);
u-=w;k.count=u;b.rowIndex=w;u?b.style.height=Math.min(u*c.rowHeight,c.maxEmptySpace)+"px":(b.style.display="none",e.count++);c._previousScrollPosition&&A&&A.offsetHeight&&(c.scrollTo(c._previousScrollPosition),delete c._previousScrollPosition);c._processScroll();c._refreshDeferred&&(c._refreshDeferred.resolve(q),delete c._refreshDeferred);return t},g)},g),q},refresh:function(d){var e=this,g=d&&d.keepScrollPosition;"undefined"===typeof g&&(g=this.keepScrollPosition);g&&(this._previousScrollPosition=
this.getScrollPosition());this.inherited(arguments);if(this.store){g=this._refreshDeferred=new B;var c=e.renderQuery(function(a){return e.store.query(e.query,a)});"undefined"===typeof c&&g.reject();return g.then(function(a){e._refreshTimeout=setTimeout(function(){P.emit(e.domNode,"dgrid-refresh-complete",{bubbles:!0,cancelable:!1,grid:e,results:a});e._refreshTimeout=null},0);delete e._refreshDeferred;return a},function(a){delete e._refreshDeferred;throw a;})}},resize:function(){this.inherited(arguments);
this._processScroll()},_getFirstRowSibling:function(d){return d.lastChild},_calcRowHeight:function(d){var e=d.nextSibling;return e&&!/\bdgrid-preload\b/.test(e.className)?e.offsetTop-d.offsetTop:d.offsetHeight},lastScrollTop:0,_processScroll:function(d){function e(m,r,G,D){var E=a.farOffRemoval,z=m.node;if(r>2*E){for(var x,J=z[G],K=0,L=0,R=[];x=J;){var S=a._calcRowHeight(x);if(K+S+E>r||0>J.className.indexOf("dgrid-row")&&0>J.className.indexOf("dgrid-loading"))break;J=x[G];K+=S;L+=x.count||1;a.removeRow(x,
!0);R.push(x)}m.count+=L;D?(z.rowIndex-=L,g(m)):z.style.height=z.offsetHeight+K+"px";var Y=n("div",R);setTimeout(function(){n(Y,"!")},1)}}function g(m,r){m.node.style.height=Math.min(m.count*a.rowHeight,r?Infinity:a.maxEmptySpace)+"px"}function c(m,r){do m=r?m.next:m.previous;while(m&&!m.node.offsetWidth);return m}var a=this,k=a.bodyNode;d=d&&d.scrollTop||this.getScrollPosition().y;k=k.offsetHeight+d;var b=a.preload,y=a.lastScrollTop,q=a.bufferRows*a.rowHeight,F=q-a.rowHeight,C,t,u,w=!0;for(a.lastScrollTop=
d;b&&!b.node.offsetWidth;)b=b.previous;for(;b&&b!=A;){var A=a.preload;a.preload=b;var f=b.node;var h=f.offsetTop;if(k+1+F<h)b=c(b,w=!1);else if(d-1-F>h+f.offsetHeight)b=c(b,w=!0);else{var l=((f.rowIndex?d-q:k)-h)/a.rowHeight;h=(k-d+2*q)/a.rowHeight;h+=Math.min(Math.abs(Math.max(Math.min((d-y)*a.rowHeight,a.maxRowsPerPage/2),a.maxRowsPerPage/-2)),10);0==f.rowIndex&&(l-=h);l=Math.max(l,0);10>l&&0<l&&h+l<a.maxRowsPerPage&&(h+=Math.max(0,l),l=0);h=Math.min(Math.max(h,a.minRowsPerPage),a.maxRowsPerPage,
b.count);if(0==h)b=c(b,w);else{h=Math.ceil(h);l=Math.min(Math.floor(l),b.count-h);var p=O.mixin(a.get("queryOptions"),b.options);b.count-=h;var v=f,H=a.queryRowsOverlap,M=(0<f.rowIndex||f.offsetTop>d)&&b;if(M){var I=b.previous;I&&(e(I,d-(I.node.offsetTop+I.node.offsetHeight),"nextSibling"),0<l&&I.node==f.previousSibling?(l=Math.min(b.count,l),b.previous.count+=l,g(b.previous,!0),f.rowIndex+=l,H=0):h+=l,b.count-=l);p.start=f.rowIndex-H;p.count=Math.min(h+H,a.maxRowsPerPage);f.rowIndex=p.start+p.count}else{if(b.next)if(e(b.next,
b.next.node.offsetTop-k,"previousSibling",!0),v=f.nextSibling,v==b.next.node)b.next.count+=b.count-l,b.next.node.rowIndex=l+h,g(b.next),b.count=l,H=0;else var N=!0;p.start=b.count;p.count=Math.min(h+H,a.maxRowsPerPage)}N&&v&&v.offsetWidth&&(N=v.offsetTop);g(b);"level"in b.query&&(p.queryLevel=b.query.level);if("queryLevel"in p||!(p.start>a._total||0>p.count)){f=n(v,"-div.dgrid-loading[style\x3dheight:"+h*a.rowHeight+"px]");n(f,"div.dgrid-"+(M?"below":"above")).innerHTML=a.loadingMessage;f.count=h;
var T=b.query(p);if(void 0===a._trackError(function(){return T})){n(f,"!");return}(function(m,r,G,D){u=B.when(a.renderArray(D,m,p),function(E){t=D;v=m.nextSibling;n(m,"!");if(G&&v&&v.offsetWidth){var z=a.getScrollPosition();a.scrollTo({x:z.x,y:z.y+v.offsetTop-G,preserveMomentum:!0})}B.when(D.total||D.length,function(x){"queryLevel"in p||(a._total=x);r&&(r.count=x-r.node.rowIndex,0===r.count&&p.count++,g(r))});a._processScroll();return E},function(E){n(m,"!");throw E;})}).call(this,f,M,N,T);b=b.previous}}}}u&&
(C=this._refreshDeferred)&&(delete this._refreshDeferred,B.when(u,function(){C.resolve(t)}))},removeRow:function(d,e){if(d){var g=d.previousSibling,c=d.nextSibling,a;if(a=g)a=g.observerIndex,a=null!=a?a:g.previousObserverIndex;g=a;if(a=c)a=c.observerIndex,a=null!=a?a:c.nextObserverIndex;c=d.observerIndex;d.observerIndex=void 0;e&&(d.nextObserverIndex=a,d.previousObserverIndex=g);if(this.cleanEmptyObservers&&-1<c&&c!==g&&c!==a&&(g=this.observers,a=g[c])){if(!e)for(var k=a.rows,b=0;b<k.length;b++)if(k[b]!=
d&&X.isDescendant(k[b],this.domNode))return this.inherited(arguments);a.cancel();this._numObservers--;g[c]=0}}this.inherited(arguments)}})});