//>>built
define("arcgisonline/map/role",["dojo","dijit","dojox","dojo/require!arcgisonline/map/main"],function(a,d,g){a.provide("arcgisonline.map.role");a.require("arcgisonline.map.main");arcgisonline.map.role={allActions:{header_newMap:!0,header_myContent:!0,tool_add:!0,tool_edit:!0,tool_edit_featCol:!0,tool_edit_mapNotes:!0,tool_save:!0,tool_share:!0,tool_bookmarks:!0,tool_bookmarks_edit:!0,tool_directions:!0,toc_menu_visibilityRange:!0,toc_menu_rename:!0,toc_menu_remove:!0,toc_menu_legend:!0,toc_menu_popup:!0,
toc_menu_refreshInterval:!0,toc_menu_move:!0,toc_menu_analysis:!0,toc_menu_saveProps:!0,toc_menu_copy:!0,toc_menu_editing:!0,toc_menu_labels:!0,toc_menu_addToBasemap:!0,about_makeOwnMap:!0,about_savePresentation:!0,share_makeWebApp:!0,share_socialMediaLinks:!0,can_esri_batch_geocoding:!0,add_require_subscription:!0,add_require_credits:!0,analysis_routing:!0,analysis_geoenrichment:!0,analysis_elevation:!0,directions_addAsLayer:!0,coachMarks:esriGeowConfig.showCoachMarksTours,coachMarks_makeMap:esriGeowConfig.showCoachMarksTours,
coachMarks_styleMap:esriGeowConfig.showCoachMarksTours,coachMarks_readyToUseLayers:esriGeowConfig.showCoachMarksTours,coachMarks_bufferPoint:esriGeowConfig.showCoachMarksTours,coachMarks_saveNotes:esriGeowConfig.showCoachMarksTours},publicActions:{header_newMap:!0,header_myContent:!0,tool_add:!0,tool_edit:!0,tool_edit_featCol:!0,tool_edit_mapNotes:!0,tool_save:!0,tool_share:!0,tool_bookmarks:!0,tool_bookmarks_edit:!0,toc_menu_visibilityRange:!0,toc_menu_rename:!0,toc_menu_remove:!0,toc_menu_legend:!0,
toc_menu_popup:!0,toc_menu_refreshInterval:!0,toc_menu_move:!0,toc_menu_saveProps:!0,toc_menu_copy:!0,toc_menu_editing:!0,toc_menu_labels:!0,toc_menu_addToBasemap:!0,about_makeOwnMap:!0,about_savePresentation:!0,share_makeWebApp:!0,share_socialMediaLinks:!0,can_esri_batch_geocoding:!0},anonymousActions:{tool_edit:!0,share_socialMediaLinks:!0,can_esri_batch_geocoding:!0},modifyMapActions:{header_newMap:!0,tool_add:!0,tool_edit:!0,tool_edit_featCol:!0,tool_edit_mapNotes:!0,tool_save:!0,tool_bookmarks:!0,
tool_bookmarks_edit:!0,toc_menu_visibilityRange:!0,toc_menu_rename:!0,toc_menu_remove:!0,toc_menu_legend:!0,toc_menu_popup:!0,toc_menu_refreshInterval:!0,toc_menu_move:!0,toc_menu_copy:!0,toc_menu_labels:!0,toc_menu_addToBasemap:!0,about_makeOwnMap:!0},useOnlyActions:{header_modifyMap:!1,tool_add:!1,tool_edit:!0,tool_edit_featCol:!1,tool_edit_mapNotes:!1,tool_save:!1,tool_bookmarks:!0,tool_bookmarks_edit:!1,tool_directions:!1,toc_menu_visibilityRange:!1,toc_menu_rename:!1,toc_menu_remove:!1,toc_menu_legend:!1,
toc_menu_popup:!1,toc_menu_refreshInterval:!1,toc_menu_move:!1,toc_menu_analysis:!1,toc_menu_saveProps:!1,toc_menu_copy:!1,toc_menu_editing:!1,toc_menu_labels:!1,toc_menu_addToBasemap:!1,directions_addAsLayer:!1,coachMarks:!1,coachMarks_makeMap:!1,coachMarks_styleMap:!1,coachMarks_readyToUseLayers:!1,coachMarks_bufferPoint:!1,coachMarks_saveNotes:!1},userActions:{},isUseOnlyMap:null,isAllowed:function(b){return arcgisonline.map.role.userActions[b]},isMapOwner:function(){var b=arcgisonline.sharing.util.getUser();
return b&&arcgisonline.map.save_open.webMapInfo&&arcgisonline.map.save_open.webMapInfo.owner===b.username?!0:!1},isAnonymous:function(b){return arcgisonline.sharing.util.getUser()?!1:!0},isPublic:function(b){return!arcgisonline.sharing.util.getUser()||esriGeowConfig.self.subscriptionInfo||arcgisonline.sharing.util.isPortal()?!1:!0},clearUserActions:function(){arcgisonline.map.role.userActions={}},setupUserActions:function(){arcgisonline.map.role._setDefaultUI();arcgisonline.map.role.isAnonymous()?
a.mixin(arcgisonline.map.role.userActions,arcgisonline.map.role.anonymousActions):arcgisonline.map.role.isPublic()?a.mixin(arcgisonline.map.role.userActions,arcgisonline.map.role.publicActions):esriGeowConfig.userRole&&arcgisonline.map.role._setupCustomActions();arcgisonline.sharing.util.isPortal()&&delete arcgisonline.map.role.userActions.coachMarks_readyToUseLayers;arcgisonline.map.role._updateUI()},_setupCustomActions:function(){esriGeowConfig.userRole.canCreateItem()?a.mixin(arcgisonline.map.role.userActions,
{header_newMap:!0,header_myContent:!0,tool_add:!0,tool_edit:esriGeowConfig.userRole.canEditFeatures(),tool_edit_featCol:esriGeowConfig.userRole.canEditFeatures(),tool_edit_mapNotes:!0,tool_save:!0,tool_share:esriGeowConfig.userRole.canShareItemToGroup()||esriGeowConfig.userRole.canShareItemToOrg()||esriGeowConfig.userRole.canShareItemToPublic(),tool_bookmarks:!0,tool_bookmarks_edit:!0,tool_directions:esriGeowConfig.userRole.canUseNetworkAnalysis(),toc_menu_visibilityRange:!0,toc_menu_rename:!0,toc_menu_remove:!0,
toc_menu_legend:!0,toc_menu_popup:!0,toc_menu_refreshInterval:!0,toc_menu_move:!0,toc_menu_analysis:arcgisonline.sharing.util.isPortal()?esriGeowConfig.userRole.canPublishFeatures()&&(esriGeowConfig.userRole.canUseSpatialAnalysis()||esriGeowConfig.userRole.canUseRasterAnalysis()||esriGeowConfig.userRole.canUseGeoanalytics()):esriGeowConfig.userRole.canPublishFeatures()&&(esriGeowConfig.userRole.canUseSpatialAnalysis()||esriGeowConfig.userRole.canUseRasterAnalysis()),toc_menu_saveProps:!0,toc_menu_copy:!0,
toc_menu_editing:esriGeowConfig.userRole.canEditFeatures(),toc_menu_labels:!0,toc_menu_addToBasemap:!0,about_makeOwnMap:!0,about_savePresentation:!0,share_makeWebApp:!0,share_socialMediaLinks:esriGeowConfig.userRole.canShareItemToPublic(),can_esri_batch_geocoding:esriGeowConfig.userRole.canUseGeocode(),add_require_subscription:!0,add_require_credits:arcgisonline.sharing.util.isPortal()?!0:esriGeowConfig.userRole.canUseDemographics(),analysis_routing:esriGeowConfig.userRole.canUseNetworkAnalysis(),
analysis_geoenrichment:esriGeowConfig.userRole.canUseGeoenrichment(),analysis_elevation:!0,analysis_geoanalytics:esriGeowConfig.userRole.canUseGeoanalytics(),analysis_raster:esriGeowConfig.userRole.canUseRasterAnalysis(),directions_addAsLayer:!0,coachMarks:esriGeowConfig.showCoachMarksTours,coachMarks_makeMap:esriGeowConfig.showCoachMarksTours&&(esriGeowConfig.userRole.canShareItemToGroup()||esriGeowConfig.userRole.canShareItemToOrg()||esriGeowConfig.userRole.canShareItemToPublic()),coachMarks_styleMap:esriGeowConfig.showCoachMarksTours,
coachMarks_readyToUseLayers:esriGeowConfig.showCoachMarksTours&&esriGeowConfig.userRole.canUseDemographics(),coachMarks_bufferPoint:esriGeowConfig.showCoachMarksTours,coachMarks_saveNotes:esriGeowConfig.showCoachMarksTours}):(delete arcgisonline.map.role.userActions.header_newMap,a.mixin(arcgisonline.map.role.userActions,{header_myContent:!0,tool_edit:esriGeowConfig.userRole.canEditFeatures(),tool_edit_featCol:!1,tool_edit_mapNotes:!0,tool_save:!1,tool_directions:esriGeowConfig.userRole.canUseNetworkAnalysis(),
directions_addAsLayer:!1,share_socialMediaLinks:esriGeowConfig.userRole.canShareItemToPublic(),can_esri_batch_geocoding:esriGeowConfig.userRole.canUseGeocode(),add_require_subscription:!0,add_require_credits:arcgisonline.sharing.util.isPortal()?!0:esriGeowConfig.userRole.canUseDemographics()}))},updateUserActionWithWebmap:function(){if(arcgisonline.map.save_open.webMapInfo){var b=arcgisonline.sharing.util.getUser();!esriGeowConfig.userRole||arcgisonline.map.save_open.webMapInfo.owner!==b.username||
esriGeowConfig.userRole.canShareItemToGroup()||esriGeowConfig.userRole.canShareItemToOrg()||esriGeowConfig.userRole.canShareItemToPublic()?arcgisonline.map.role.userActions.tool_share=!0:delete arcgisonline.map.role.userActions.tool_share;arcgisonline.map.role._checkUseOnlyMap().then(function(c){c?(arcgisonline.map.role.isUseOnlyMap=!0,a.mixin(arcgisonline.map.role.userActions,arcgisonline.map.role.useOnlyActions),arcgisonline.map.role.isAnonymous()||(arcgisonline.map.role.userActions.header_newMap=
!0),(c=arcgisonline.map.save_open.openedWebMap)&&c.bookmarks&&c.bookmarks.length?arcgisonline.map.role.userActions.tool_bookmarks=!0:delete arcgisonline.map.role.userActions.tool_bookmarks):(arcgisonline.map.role.isUseOnlyMap=!1,arcgisonline.map.role.isAnonymous()||esriGeowConfig.userRole&&!esriGeowConfig.userRole.canCreateItem()?(delete arcgisonline.map.role.userActions.header_newMap,arcgisonline.map.save_open.webMapInfo&&"update"===arcgisonline.map.save_open.webMapInfo.itemControl?(a.mixin(arcgisonline.map.role.userActions,
arcgisonline.map.role.modifyMapActions),arcgisonline.map.role.userActions.header_newMap=!1,arcgisonline.map.role.userActions.about_makeOwnMap=!1,esriGeowConfig.userRole&&a.mixin(arcgisonline.map.role.userActions,{tool_share:arcgisonline.map.save_open.webMapItemCard,toc_menu_editing:!0,directions_addAsLayer:esriGeowConfig.userRole.canCreateItem()}),"contentStack"===arcgisonline.map.leftPanel.getLeftContentPanelStack()&&leftPanel.reloadVisibleTOC(),arcgisonline.map.dijit.toc.dnd.setup(arcgisonline.map.dijit.toc.dnd._dndSourceNode)):
(arcgisonline.map.role.userActions.header_modifyMap=!0,(c=arcgisonline.map.save_open.openedWebMap)&&c.bookmarks&&c.bookmarks.length&&(arcgisonline.map.role.userActions.tool_bookmarks=!0))):arcgisonline.map.role.userActions.header_newMap=!0,leftPanel&&leftPanel.checkAboutStack());arcgisonline.map.role._updateUI()})}else{if(arcgisonline.map.role.isAnonymous()||esriGeowConfig.userRole&&!esriGeowConfig.userRole.canCreateItem())delete arcgisonline.map.role.userActions.header_newMap,arcgisonline.map.role.userActions.header_modifyMap=
!0;leftPanel&&leftPanel.checkAboutStack();arcgisonline.map.role._updateUI()}},updateUserActionAfterModify:function(b){b&&b.preventDefault();delete arcgisonline.map.role.userActions.header_modifyMap;arcgisonline.map.role.userActions.header_newMap=!0;arcgisonline.map.save_open.webMapItemCard||arcgisonline.map.save_open.itemCard||"undefined"===typeof leftPanel||leftPanel.checkAboutStack();"contentStack"==arcgisonline.map.leftPanel.getLeftContentPanelStack()?leftPanel.reloadVisibleTOC():leftPanel.deleteContentStack();
a.mixin(arcgisonline.map.role.userActions,arcgisonline.map.role.modifyMapActions);if(esriGeowConfig.userRole&&(b=!1,esriGeowConfig.userRole.canCreateItem()&&(esriGeowConfig.userRole.canShareItemToGroup()||esriGeowConfig.userRole.canShareItemToOrg()||esriGeowConfig.userRole.canShareItemToPublic())&&(b=!0),a.mixin(arcgisonline.map.role.userActions,{tool_edit:arcgisonline.map.role.userActions.tool_edit,tool_edit_featCol:esriGeowConfig.userRole.canEditFeatures(),tool_edit_mapNotes:!0,tool_save:esriGeowConfig.userRole.canCreateItem(),
tool_share:arcgisonline.map.save_open.webMapItemCard||b,toc_menu_editing:esriGeowConfig.userRole.canEditFeatures(),directions_addAsLayer:esriGeowConfig.userRole.canCreateItem()}),arcgisonline.sharing.util.getUser()&&esriGeowConfig.userRole&&!esriGeowConfig.userRole.canEditFeatures())){var c=!1;a.forEach(arcgisonline.map.main.mapLayers,function(e){!e.itemCard||"update"!==e.itemCard.itemControl&&"admin"!==e.itemCard.itemControl||(c=!0)});c&&(arcgisonline.map.role.userActions.tool_edit=!0)}arcgisonline.map.role._updateUI();
arcgisonline.map.dijit.toc.dnd._dndSourceNode&&arcgisonline.map.dijit.toc.dnd.setup(arcgisonline.map.dijit.toc.dnd._dndSourceNode);a.publish("onLayerUpdate",[""])},updateUserActionAfterOAuth:function(){esriGeowConfig.userRole&&!esriGeowConfig.userRole.canCreateItem()&&"update"===arcgisonline.map.save_open.webMapInfo.itemControl&&(arcgisonline.map.role.userActions.tool_save=!0,arcgisonline.map.role.userActions.tool_bookmarks=!0,arcgisonline.map.role.updateUserActionAfterModify())},updateUserActionAfterFullEditing:function(){arcgisonline.map.role.userActions.tool_edit=
!0},_setDefaultUI:function(){a.style(a.byId("header_map_recentMaps"),"display","none");a.style(a.byId("header_map_modifyMap"),"display","none");a.style(a.byId("header_map_newMap"),"display","none");a.style(d.byId("webmap-add").domNode,"display","none");a.style(d.byId("webmap-save").domNode,"display","none");a.style(d.byId("webmap-share").domNode,"display","none");a.style(d.byId("webmap-bookmarks").domNode,"display","none");a.style(d.byId("webmap-directions").domNode,"display","none");arcgisonline.map.role.isAnonymous()||
esriGeowConfig.userRole&&!esriGeowConfig.userRole.canCreateItem()||a.query(".homeMyContent",this.domNode).removeClass("hide");arcgisonline.map.main.checkMinWidthOfPage()},_updateUI:function(){var b=10>a.isIE?"inline-block":"";arcgisonline.map.role.isAllowed("header_newMap")?a.style(a.byId("header_map_newMap"),"display",b):a.style(a.byId("header_map_newMap"),"display","none");arcgisonline.map.main.updateRecentWebMaps();arcgisonline.map.role.isAllowed("header_modifyMap")?a.style(a.byId("header_map_modifyMap"),
"display",b):a.style(a.byId("header_map_modifyMap"),"display","none");arcgisonline.map.role.isAllowed("tool_add")?a.style(d.byId("webmap-add").domNode,"display",b):a.style(d.byId("webmap-add").domNode,"display","none");isEmbedded&&isEmbedded.hideSave||!arcgisonline.map.role.isAllowed("tool_save")?a.style(d.byId("webmap-save").domNode,"display","none"):(a.style(d.byId("webmap-save").domNode,"display",b),esriGeowConfig.userRole&&!esriGeowConfig.userRole.canCreateItem()&&d.byId("webmap-save-saveas").set("disabled",
!0));isEmbedded&&isEmbedded.hideBookmarks||!arcgisonline.map.role.isAllowed("tool_bookmarks")?a.style(d.byId("webmap-bookmarks").domNode,"display","none"):(a.style(d.byId("webmap-bookmarks").domNode,"display",b),arcgisonline.map.role.checkBookmarksToolOptions());isEmbedded&&isEmbedded.hideShare||!arcgisonline.map.role.isAllowed("tool_share")?a.style(d.byId("webmap-share").domNode,"display","none"):a.style(d.byId("webmap-share").domNode,"display",b);arcgisonline.map.main.isMapFullyLoaded&&!isEmbedded&&
arcgisonline.map.role.canShowDirections()?a.style(d.byId("webmap-directions").domNode,"display",b):a.style(d.byId("webmap-directions").domNode,"display","none");arcgisonline.map.edit.checkOnEditButton();arcgisonline.map.dijit.toc.analysis.checkOnAnalysisButton();arcgisonline.map.main.updateRecentWebMaps();arcgisonline.map.main.checkMinWidthOfPage()},checkBookmarksToolOptions:function(){arcgisonline.map.role.isAllowed("tool_bookmarks_edit")?(a.query(".esriAddBookmark").forEach(function(b){a.style(b,
"display","")}),a.query(".esriBookmarkRemoveImage").forEach(function(b){a.style(b,"display","")}),a.query(".esriBookmarkEditImage").forEach(function(b){a.style(b,"display","")})):(a.query(".esriAddBookmark").forEach(function(b){a.style(b,"display","none")}),a.query(".esriBookmarkRemoveImage").forEach(function(b){a.style(b,"display","none")}),a.query(".esriBookmarkEditImage").forEach(function(b){a.style(b,"display","none")}))},canShowDirections:function(){return arcgisonline.map.role.isAllowed("tool_directions")&&
esriGeowConfig.self.helperServices.route&&esriGeowConfig.self.helperServices.route.url?!0:!1},updateUIAfterSaveAs:function(){!esriGeowConfig.userRole||esriGeowConfig.userRole.canShareItemToGroup()||esriGeowConfig.userRole.canShareItemToOrg()||esriGeowConfig.userRole.canShareItemToPublic()||(delete arcgisonline.map.role.userActions.tool_share,arcgisonline.map.role._updateUI())},_checkUseOnlyMap:function(){var b=new a.Deferred;arcgisonline.map.save_open.webMapItemCard=arcgisonline.map.save_open.webMapItemCard||
arcgisonline.map.save_open.webMapInfo;var c=arcgisonline.map.save_open.webMapItemCard;if(c&&-1<a.indexOf(c.typeKeywords,"useOnly")){var e=arcgisonline.sharing.util.getUser();e&&c.owner===e.username?b.callback(!1):"admin"===c.itemControl||"update"===c.itemControl?b.callback(!1):esriGeowConfig.userRole&&esriGeowConfig.userRole.isAdmin()?esri.isDefined(c.accountId)?c.accountId===e.accountId?b.callback(!1):b.callback(!0):arcgisonline.sharing.geow.Community.getProfile(c.owner,a.hitch(this,a.hitch(this,
function(f,h){f.orgId?(c.accountId=f.orgId!==e.accountId?-1:f.orgId,b.callback(!1)):(c.accountId=-1,b.callback(!0))})),a.hitch(this,function(){b.callback(!0)})):b.callback(!0)}else b.callback(!1);return b}}});